- name: variables to print 
  hosts: web 
  vars: 
    course: "java"
    duration: "10hrs"
    trainer: "ravi kumar"
  tasks: 
  - name: print the info 
    ansible.builtin.debug: 
      msg: "hi i am learining {{course}}, duration is {{duration}}, trainer is {{trainer}}" 