- name: devops course information
  hosts: local
  connection: local
  vars:
    course: "devops with aws"  #string
    duration: 120   #number
    topics: 
    - linux
    - shell
    - ansible
    - terraform
    - aws
    live: true  #boolean
    tools:  #map/dictionary
      ci: jenkins
      cm: ansible
      cloud: aws
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "hi i am learning {{course}} with {{duration}}, topics are {{topics}}, and live: {{live}}, tools are: {{tools}}"