- name: install nginx
  hosts: web 
  become: yes
  tasks: 
  - name: print the facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"
  
  - name: install nginx if redhat 
    ansible.builtin.dnf: 
      name: nginx
      state: present
    when: ansible_os_family == "redhat"

  - name: install nginx if debian
    anisble.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "debian"
    