- name: installing packages through loops
  hosts: web
  become: yes
  tasks:
  - name: print package names
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql 
    - nginx
    - postfix