- name: functions demo 
  hosts: web 
  tasks: 
  - name: print the varialble 
    ansible.builtin.debug:
      msg: "hello {{ course | default('ansible') }}"
  
  - name: convert to upper case 
    vars: 
      greeting: "hello RAMESH"
    ansible.builtin.debug:
      msg: " {{ greeting | upper }} "
